# 关闭防火墙、设置主机名、内核优化
- hosts: all-server
  tags: init
  roles:
    - role: init
# 安装docker
- hosts: k8s
  tags: docker
  roles:
    - role: docker
# 安装harbor
- hosts: harbor
  tags: harbor
  roles:
    - role: harbor

# 加入k8s集群
- hosts: join-worker
  tags: join-worker
  roles:
    - role: join-worker

# 移除k8s集群
- hosts: remove-worker
  tags: remove-worker
  roles:
    - role: remove-worker


