---
- name: 检查节点是否存在于集群中
  shell: kubectl get nodes | grep {{ host_name }}
  register: node_exists
  delegate_to: "{{ hostvars[groups['k8s'] | selectattr('k8s_role', 'equalto', 'master') | first]['ansible_host'] }}"
  failed_when: false
  changed_when: false

- name: 标记节点为不可调度
  shell: kubectl cordon {{ host_name }}
  delegate_to: "{{ hostvars[groups['k8s'] | selectattr('k8s_role', 'equalto', 'master') | first]['ansible_host'] }}"
  when: node_exists.rc == 0

- name: 驱逐节点上的Pod
  shell: kubectl drain {{ host_name }} --ignore-daemonsets --delete-emptydir-data --force
  delegate_to: "{{ hostvars[groups['k8s'] | selectattr('k8s_role', 'equalto', 'master') | first]['ansible_host'] }}"
  when: node_exists.rc == 0

- name: 等待Pod迁移完成
  pause:
    seconds: 60
  when: node_exists.rc == 0

- name: 检查节点状态
  shell: kubectl get nodes {{ host_name }}
  register: node_status
  delegate_to: "{{ hostvars[groups['k8s'] | selectattr('k8s_role', 'equalto', 'master') | first]['ansible_host'] }}"
  when: node_exists.rc == 0

- name: 显示节点状态
  debug:
    msg: "{{ node_status.stdout }}"
  when: node_exists.rc == 0 