---
- name: 从集群中删除节点
  shell: kubectl delete node "{{ host_name }}"
  delegate_to: "{{ groups['k8s'][0] }}"
  when: node_exists.rc == 0

- name: 验证节点已删除
  shell: kubectl get nodes | grep "{{ host_name }}"
  register: node_removed
  delegate_to: "{{ groups['k8s'][0] }}"
  failed_when: false
  changed_when: false

- name: 确认节点删除结果
  debug:
    msg: "节点 {{ host_name }} 已成功从集群中删除"
  when: node_removed.rc != 0

- name: 显示当前集群节点列表
  shell: kubectl get nodes
  register: cluster_nodes
  delegate_to: "{{ groups['k8s'][0] }}"

- name: 显示集群节点状态
  debug:
    msg: "{{ cluster_nodes.stdout }}" 