---
- name: 停止cri-docker服务
  systemd:
    name: cri-docker
    state: stopped
    enabled: no
  ignore_errors: yes

- name: 停止Docker服务
  systemd:
    name: docker
    state: stopped
    enabled: no
  ignore_errors: yes

- name: 卸载cri-dockerd包
  yum:
    name: cri-dockerd
    state: absent
  when: uninstall_cri_dockerd | default(true)
  ignore_errors: yes

- name: 删除Docker二进制文件
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /usr/bin/docker
    - /usr/bin/docker-containerd
    - /usr/bin/docker-containerd-ctr
    - /usr/bin/docker-containerd-shim
    - /usr/bin/docker-init
    - /usr/bin/docker-proxy
    - /usr/bin/dockerd
  when: uninstall_docker | default(true)

- name: 删除Docker服务文件
  file:
    path: /etc/systemd/system/docker.service
    state: absent
  when: uninstall_docker | default(true)

- name: 删除Docker数据目录
  file:
    path: "{{ docker_home_dir | default('/var/lib/docker') }}"
    state: absent
  when: clean_docker_data | default(true)

- name: 删除Docker配置目录
  file:
    path: /etc/docker
    state: absent
  when: clean_docker_config | default(true)

- name: 删除Docker临时文件
  file:
    path: /opt/docker
    state: absent
  when: uninstall_docker | default(true)

- name: 卸载Kubernetes组件
  yum:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: absent
  when: uninstall_k8s | default(true)
  ignore_errors: yes

- name: 删除docker用户组
  group:
    name: docker
    state: absent
  when: uninstall_docker | default(true)
  ignore_errors: yes

- name: 重新加载systemd配置
  systemd:
    daemon_reload: yes
  when: uninstall_docker | default(true) or uninstall_cri_dockerd | default(true)

- name: 显示清理完成信息
  debug:
    msg: "工作节点 {{ host_name }} 已完成清理"