---
- name: 等待Master节点准备就绪
  wait_for:
    host: "{{ groups['k8s'][0] }}"
    port: 6443
    delay: 10
    timeout: 300

- name: 在Master节点生成加入命令
  shell: kubeadm token create --print-join-command > /tmp/join-command.sh
  delegate_to: "{{ groups['k8s'][0] }}"

- name: 检查Master节点上的join命令文件
  stat:
    path: /tmp/join-command.sh
  delegate_to: "{{ groups['k8s'][0] }}"
  register: join_file_master

- name: 显示Master节点文件信息
  debug:
    msg: "Master节点join文件存在: {{ join_file_master.stat.exists }}"
  when: join_file_master.stat.exists

- name: 显示join命令内容
  shell: cat /tmp/join-command.sh
  delegate_to: "{{ groups['k8s'][0] }}"
  register: join_command_content
  when: join_file_master.stat.exists

- name: 显示join命令
  debug:
    msg: "{{ join_command_content.stdout }}"
  when: join_file_master.stat.exists

- name: 将join命令写入worker节点文件
  copy:
    content: "{{ join_command_content.stdout }}"
    dest: /tmp/join-command.sh
    mode: '0755'
  when: join_file_master.stat.exists

- name: 检查worker节点上的join命令文件
  stat:
    path: /tmp/join-command.sh
  register: join_file_worker

- name: 显示worker节点文件信息
  debug:
    msg: "Worker节点join文件存在: {{ join_file_worker.stat.exists }}"

- name: 预拉取必要的镜像
  shell: |
    docker pull {{ harbor_host }}:{{ harbor_port }}/k8s/kube-proxy:v1.28.15
    docker pull {{ harbor_host }}:{{ harbor_port }}/k8s/pause:3.10
    docker pull {{ harbor_host }}:{{ harbor_port }}/calico/cni:v3.24.1
    docker pull {{ harbor_host }}:{{ harbor_port }}/calico/node:v3.24.1
  when: join_file_worker.stat.exists

- name: 工作节点加入集群
  shell: "bash /tmp/join-command.sh --cri-socket=unix:///var/run/cri-dockerd.sock"
  when: join_file_worker.stat.exists

# - name: 重新打标签工作节点镜像
#   shell: |
#     docker tag /k8s/kube-proxy:v1.28.15 {{ harbor_host }}:{{ harbor_port }}/k8s/kube-proxy:v1.28.15
#     docker tag registry.k8s.io/pause:3.10 {{ harbor_host }}:{{ harbor_port }}/k8s/pause:3.10
#     docker tag {{ harbor_host }}:{{ harbor_port }}/calico/cni:v3.24.1 {{ harbor_host }}:{{ harbor_port }}/calico/cni:v3.24.1
#     docker tag {{ harbor_host }}:{{ harbor_port }}/calico/node:v3.24.1

- name: 检查节点状态
  shell: kubectl get nodes
  register: node_status
  delegate_to: "{{ groups['k8s'][0] }}"

- name: 显示节点状态
  debug:
    msg: "{{ node_status.stdout }}" 