---
- name: 解压Docker安装包
  unarchive:
    src: /opt/files/docker/docker-28.2.2.tgz
    dest: /opt
    remote_src: yes

- name: 将Docker二进制文件移动到/usr/bin
  copy:
    src: /opt/docker/
    dest: /usr/bin/
    mode: '0755'
    remote_src: yes

- name: 清理临时文件
  file:
    path: /opt/docker
    state: absent

- name: 创建Docker服务文件
  template:
    src: docker.service.j2
    dest: /etc/systemd/system/docker.service

- name: 重新加载systemd配置
  systemd:
    daemon_reload: yes

- name: 启动Docker服务
  systemd:
    name: docker
    state: started
    enabled: yes

- name: 检查Docker服务状态
  systemd:
    name: docker
  register: docker_status

- name: 显示Docker服务状态
  debug:
    msg: "Docker服务状态: {{ docker_status.status.ActiveState }}"
